name: build-and-test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    # At 23:25 on Thursday.
    - cron: "25 23 * * 4"

jobs:
  default:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '2.x', '3.x' ]
        exclude:
          # excludes python 2.x on Windows
          - os: windows-latest
            python-version: '2.x'

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Build
      run: python -m pip install .
    - name: Test
      run: python -c "import cgtypes; cgtypes.vec3(1.0, 2.0, 3.0)"
